rttm_split_char = " 1 "
rttm_end_of_req_info = "\n"
info_needed_char = "_"
noise_char = "<NA>"
spearker_info_start = "SPEAKER"
wav_suff = ".wav"
csv_suff = ".csv"
audio_file_dir = "audio" 
audio_wav_dir = "audiowav"
rm_dir = "audiorttm"
link_col = "Link"
audio_dir = "audio" 
transcripts_dir = "transcripts" 
speaker_col = "Speaker"
text_col = "Text"
title_col_speakers = "title"
words_col = "words"
ousiowords = "word"
ousiopower = "power"
ousiodanger = "danger"
power_index = 1
danger_index = 2
crim_col = "name"
ncols = 3
final_df = "final_words.csv"
sparse_rows = ["Alvaro Castillo", "Kenneth Bartley", "Andy Williams", "James Holmes"]
ousio_dat = "ousiometry_data_augmented.tsv"
window_size = 50
colors = ["darkorchid", "crimson"]
dash_colrs = ["lightsteelblue", "lavender"]
lin_styles = ["--", "-"]